[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/paystack-webhook"
  to = "/.netlify/functions/paystack-webhook"
  status = 200

[[redirects]]
  from = "/api/orders"
  to = "/.netlify/functions/get-orders"
  status = 200
